### ISSUE TITLE
Дополнение занимает место в резервных копиях

### ISSUE THREAD

**Issue by KaportsevIA** [maxifly/YaBackupAddon#10]
Добрый день! Дополнение Yandex Backup занимает много места в резервной копии. Если до его установки полный бэкап ХА весил от 50 до 100 МБайт, то сейчас более 250МБайт. При том что вся БД ХА весит всего 130Мбайт.

**Comment by maxifly** [comment]
Интересно. Посмотрю.

**Comment by maxifly** [comment]
Я вот прямо сильно подозреваю, что это от того, что я не собираю и  не кладу собранный докер-имадж в репозиторий.
И поэтому в бакап тянутся все зависимости для имаджа (видимоБ для тогоБ чтобы восстановить его прям таким же как на момент бакапа)
(Собирать и класть в репозиторий никогда не пробовал. ВОт пытаюсь понятькак это делается)

**Comment by maxifly** [comment]
Да. Похоже использование собранных образов решает проблему.

ДО использования собранных образов размер  аддона в полном бэкапе составлял 133M
ПОСЛЕ 2K

**Comment by maxifly** [comment]
Ну раз возражений нет, я закрываю.
