### ISSUE TITLE
Дифференциальное резервное копирование

### ISSUE THREAD

**Issue by ixmax** [maxifly/YaBackupAddon#13]
В настоящее время аддон делает копирование того, что есть в папке, без сверки с ЯД.
Если старые бэкапы хранятся в ХА, то аддон каждый день будет этот бэкап заново заливать в папку ЯД. Заметил это существенным увеличением потребления ежедневного трафика.
Болезненно для тех, у кого лимитирован мобильный трафик на загородном ХА.

Для примера: сейчас у меня ежедневный расход 4+Гб трафика на бэкап, когда один бэкап весит около 120Мб.

**Comment by maxifly** [comment]
Вообще-то со сверкой. То что уже лежит в ЯД второй раз не льётся. Может у вас настроено хранение на ЯД меншего количества бэкапов, чем в ХА и он каждый день льёт, удаляет из ЯД и поэтому на следующий деньзаново льёт?

**Comment by ixmax** [comment]
> Вообще-то со сверкой. То что уже лежит в ЯД второй раз не льётся. Может у вас настроено хранение на ЯД меншего количества бэкапов, чем в ХА и он каждый день льёт, удаляет из ЯД и поэтому на следующий деньзаново льёт?

remote_maximum_files_quantity = 100
В папке ЯД - 50 файлов на сегодня. В ХА бэкапов 176
Заметил странное поведение:
скорее всего аддон удаляет бэкап в ЯД, а на следующий день его заливает. В истории изменений старых файлов идет журнал - загрузка - удаление - загрузка - удаление и т.д. через день.
Поэтому за сегодня (10.10) и за вчера (09.10) бэкап на ЯД есть, но за 07.10 нет (удален скорее всего), а за 06.10 есть. И у файла за 06.10 история:
![image](https://github.com/user-attachments/assets/3ddbd7e9-b219-4c3f-b672-f5197ec4ae9d)
Правильнее было бы удалять в ЯД более старое, а лучше триггер - удалять старое или забивать ЯД под завязку.

**Comment by maxifly** [comment]
> Правильнее было бы удалять в ЯД более старое
Так и делается. Сортировка ведётся по времени модификации файла (заливки)
https://github.com/maxifly/YaBackupAddon/blob/88b16ffc65e60c1ba117ad09cfca7d7a74662ca0/yabackup/src/bk_file_processing.go#L104

Заливаются файлы в порядке времени создания (старые вперёд)

Параметр remote_maximum_files_quantity у Вас чему равен?
