### ISSUE TITLE
sensor.yandex_backup_state пропадает после перезагрузки Home Assistant

### ISSUE THREAD

**Issue by dmitkam** [maxifly/YaBackupAddon#14]
sensor.yandex_backup_state пропадает после перезагрузки Home Assistant

До перезагрузки:

success_upload_files: 1
error_upload_files: 0
success_delete_files: 1
error_delete_files: 0
remote_files: 5
local_files: 5
remote_file_size: 1670072320
local_file_size: 1663928320
remote_free_space: 37529706829
last_upload_time: 2024-10-21T14:37:39.218566851+03:00

Если снова войти в WEB-интерфейс -  появляется, но без актуальных данных:

success_upload_files: 0
error_upload_files: 0
success_delete_files: 0
error_delete_files: 0
remote_files: 5
local_files: 5
remote_file_size: 1670072320
local_file_size: 1663928320
remote_free_space: 37529706829
last_upload_time: 0001-01-01T00:00:00Z

Можно ли сделать так чтобы восстанавливались данные до перезагрузки, хотя бы  last_upload_time.

**Comment by maxifly** [comment]
да, я тоже это уже заметил. 
Ситуация даже хуже, если в WEB-интерфейс аддона не заходить такого сенсора после перезагрузки вообще нет.
Настройками никак не вывести. Надо будет доработать код.

**Comment by maxifly** [comment]
Исправил.
1 Обновите аддон.
2 Либо сделайте Upload вручную, либо дождитесь пока он сам произойдёт
После этого состояние точно будет восстанавливаться при перезагрузке сервера

**Comment by dmitkam** [comment]
Обновил. Всё так же.(

**Comment by maxifly** [comment]
Странно. У меня заработало.
Убедитесь, что уровень логирования в аддоне не ниже INFO
Рестартаните сервер, подождите минут пять, зайдите в веб-интерфейс аддона, нажмите кнопку Download log
Скачанный лог приложите к этому обсуждению

**Comment by dmitkam** [comment]
нет только перезагрузку НА

![image](https://github.com/user-attachments/assets/3bc70a0c-7513-45e0-b981-287915e438ab)

**Comment by dmitkam** [comment]
Лог

[ybg.log](https://github.com/user-attachments/files/17527895/ybg.log)

**Comment by maxifly** [comment]
Тогда погодите пока с логом.

**Comment by maxifly** [comment]
Да. У меня тоже повторяется ситуация. 
Что интересно, похоже от GoogleBackup тоже состояние теряется.
Но я придумал, как сделать

**Comment by maxifly** [comment]
Ну, надеюсь, что со второго захода я все случаи закрыл.
Добавил фоновую задачу, которая раз в 30 сек проверяет наличие entity. И если его нет восстанавливает из локальной копии. Я так понимаю, что это единственный путь, потому что из аддона невозможно как-либо подписаться на нотификацию о рестарте HA

**Comment by dmitkam** [comment]
Обновить не удается. Зависает.
После принудительном перезапуске НА - не остановить, не обновить. 


Регистратор: homeassistant.components.hassio
Источник: components/hassio/websocket_api.py:135
интеграция: Home Assistant Supervisor (документация, проблемы)
Первое сообщение: 20:41:33 (3 сообщений)
Последнее сообщение: 20:44:56

Failed to to call /addons/38c0dd1e_yabackup/stop - Another job is running for job group addon_38c0dd1e_yabackup
Failed to to call /store/addons/38c0dd1e_yabackup/update - Another job is running for job group addon_38c0dd1e_yabackup

**Comment by maxifly** [comment]
Ну раз вестей нет, видимо всё исправил
