### ISSUE TITLE
Периодичность копирования на ЯндексДиск

### ISSUE THREAD

**Issue by dmitkam** [maxifly/YaBackupAddon#16]
Периодичность копирования на ЯндексДиск.
Установлено: 1 5 * * *  (каждый день в 5:01)
![image](https://github.com/user-attachments/assets/dade7239-02cf-4547-84ac-183e40597c65)
Копирование происходит +3 часа
![image](https://github.com/user-attachments/assets/233135c2-7cad-47c2-9c15-589302bda6f7)
![image](https://github.com/user-attachments/assets/ea216a5f-0caf-4659-8f8b-a97ce148db51)

**Comment by maxifly** [comment]
Да. Так и будет. Потому что внутри аддона установлена таймзона UTC.
Вам надо давать поправку.

**Comment by dmitkam** [comment]
Спасибо. Понял.
Ещё один вопрос - можно ли вызывать копирование из автоматизации НА?

**Comment by maxifly** [comment]
> Спасибо. Понял. Ещё один вопрос - можно ли вызывать копирование из автоматизации НА?

Нет. Такая возможность не предусмотрена.
