### ISSUE TITLE
Безумное потребление RAM

### ISSUE THREAD

**Issue by evil-err0r** [maxifly/YaBackupAddon#5]
Начиная с версии v1.2.0 выросло потреблении RAM до немыслимых значений.

Требует для запуска минимум 2,5Г и после запуска, съедает всю доступную память.

![image](https://github.com/maxifly/YaBackupAddon/assets/74493954/a6f6f64a-213b-4125-9db3-08267f47e20d)

**Comment by maxifly** [comment]
Несколько вопросов:
1. Он прямо сразу съедает?
2. Что вернёт выполненная на хосте команда
docker ps -as|grep yabackup
3. Пришлите параметры Вашей конфигурации
remote_maximum_files_quantity и 
schedule

**Comment by maxifly** [comment]
Посмотрел у себя. Тоже растёт
raspberrypi:~ $ docker ps -as|grep backup
293d2184f7d9   38c0dd1e/aarch64-addon-yabackup:1.2.1                            "/init /usr/bin/supe…"   15 seconds ago   Up 14 seconds  
.....

raspberrypi:~ $ docker ps -as|grep yabackup
293d2184f7d9   38c0dd1e/aarch64-addon-yabackup:1.2.1                            "/init /usr/bin/supe…"   3 minutes ago   Up 3 minutes                                                                                                                                           addon_38c0dd1e_yabackup                     53.1kB (virtual 472MB)

**Comment by evil-err0r** [comment]
> Несколько вопросов:
> 
> 1. Он прямо сразу съедает?
> 2. Что вернёт выполненная на хосте команда
>    docker ps -as|grep yabackup
> 3. Пришлите параметры Вашей конфигурации
>    remote_maximum_files_quantity и
>    schedule

1. Да сразу при запуске потребление показывает 80+% и общее потребление системы 95+%

С запущенным приложением.
![image](https://github.com/maxifly/YaBackupAddon/assets/74493954/a3ef997b-e5d7-4ec4-8591-fd58be153919)

Приложение выключено.
![image](https://github.com/maxifly/YaBackupAddon/assets/74493954/c251f914-024a-4203-9d6b-d760aec0c9fb)

На RP3 B+ v1.2.0 вообще не запускается, ругаясь что для запуска необходимо 2,5Г памяти.

2. hasio не понимает данную команду.


3. remote_maximum_files_quantity: 2
schedule: 1 4 * * *

**Comment by maxifly** [comment]
Да. Повторилась ошибка на hassio:
![image](https://github.com/maxifly/YaBackupAddon/assets/2596114/29d1c1dc-e16c-473f-9b40-cfe0842a2c56)

А на конфигурации типа Supervised такого явления нет

**Comment by maxifly** [comment]
Вернулся к использованию WSGI встроенного во flask.
Должно быть хорошо.
Пока оставлю открытым.
По возможности отпишитесь ушла проблема или нет.
