### ISSUE TITLE
Проблема с темной темой HA

### ISSUE THREAD

**Issue by wisemars** [maxifly/YaBackupAddon#8]
Абсолютно ничего не видно в веб-интерфейсе Аддона при использовании темной темы Home Assistant
![image](https://github.com/maxifly/YaBackupAddon/assets/25186900/cf4dfdec-362d-4f3c-a27e-929d38d39bfb)

**Comment by maxifly** [comment]
Интересная штука. Даже не знал, что такое надо учитывать. Спасибо. Попробую разобраться.

**Comment by maxifly** [comment]
Изменил css. Кроме того, добавил параметр в конфигурацию, позволяющий перейти на тёмную тему (Не знаю точно, как HA отслеживает мзменения структуры конфига. Возможно, чтобы новый параметр появился потребуется удалить и заново поставить аддон)

**Comment by maxifly** [comment]
Да. Подтверждаю. 
Мне никак не удалось заставить браузер перечитать main.css
И поэтому проблема с использованием аддона с темой Light, когда в HA стоит тема Dark сохраняется до тех пор, пока аддон не будет удалён и поставлен заново.

**Comment by wisemars** [comment]
Большое спасибо за фикс)
